### ISSUE TITLE
OOM policy "continue" not supported in Centos/Rocky linux 8

### ISSUE THREAD

**Issue by caseybea** [jupyterhub/systemdspawner#105]
I have a server running Rocky Linux 8 (basically, Centos 8..).  Systemd version is **239**.

The sudospawner logs this error when starting up:

jupyterhub[352620]: Unknown assignment: OOMPolicy=continue

This causes the systemdspawner to time-out when firing up the user's spawned environment.   Users cannot start their hubs.

commenting out the line below from "systemd.py" provided by the package seems to work.   But I fear for side-effects.
properties.setdefault('OOMPolicy', 'continue')

**Comment by caseybea** [comment]
After a whole bunnch more testing, it seems to me that even the systemd version with RedHat8/Rocky8/Almalinux8 etc is not sufficient.    The OOMPolicy thing is somehow not supported, apparently.

I was able to get it to work (and no errors) under Rocky9(akaRedHat9,Alma9, etc).

I highly suggest the documentation be updated to reflect that you need Redhat8/Rocky9/etc for that class OS for this to work.

(PS: It could POSSIBLY work with Centos STREAM 8, I have not tried and most people do not use Stream 8 for production..)

**Comment by consideRatio** [comment]
Ah, so this makes things crash on systemd sometime between version 239 (rocky 8, doesn't work) and 252 (rocky 9, works).

> The sudospawner logs this error when starting up:
>
>jupyterhub[352620]: Unknown assignment: OOMPolicy=continue
>
>This causes the systemdspawner to time-out when firing up the user's spawned environment. Users cannot start their hubs.

It seems that ubuntu 18.04's man pages for systemd 237 doesn't include OOMPolicy, but ubuntu 20.04 does with systemd 245. So, maybe this was introduced between 239 and 245 somtime?

**Comment by consideRatio** [comment]
It seems that it was introduced in v243, so it seems we need v243 to function currently. See https://github.com/systemd/systemd/commit/afcfaa695cd00b713e7d57e1829da90b692ac6f8.
