### ISSUE TITLE
What Linux distributions to test against?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/systemdspawner#106]
We use systemdspawner in TLJH, which supports running in debian 11 and ubuntu 20.04 and 22.04 currently. So, testing systemdspawner in at least one of those makes sense to me.

Is there some other distro we want to test against? Otherwise I figure we settle for testing Debian or Ubuntu only.

**Comment by yuvipanda** [comment]
"Last but one Ubuntu LTS" is perhaps what to test. So that would be Ubuntu 20.04 now, and Ubuntu 22.04 once 24.04 comes out. That should give us a nice 'minimum systemd version' to test against.
