### ISSUE TITLE
Run test suite with a GitHub Workflow

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/systemdspawner#107]
I figure this spawner require a systemd environment setup in various linux distributions, but we can get that done I think. We are using this spawner in the TLJH distribution where a basic systemd image built and tljh is installed within the image with systemd.

See the Dockerfile that installs systemd here:
https://github.com/jupyterhub/the-littlest-jupyterhub/blob/main/integration-tests/Dockerfile

**Comment by behrmann** [comment]
As a word of warning: docker had some animosity towards systemd in the past and went out of its way to make it hard to run systemd inside a container and is probably the last container runtime to not support systemd's [container interface](https://systemd.io/CONTAINER_INTERFACE/). You will probably have more luck running your tests with podman, which in most cases should be drop-in compatible.

That being said, GA run in Ubuntu VMs and just have systemd installed. systemd-spawner doesn't use any too recent featuees, so any recent Ubuntu LTS should be fine.
