### ISSUE TITLE
Add ability to set aside a slice for all the single user servers

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/systemdspawner#11]
If we spawn all single user notebooks into a slice and set cpu / memory limits on that slice, we can guarantee that notebook users can never, individually or in aggregate, OOM a machine.

Ideally we would also be able to just create the slice transiently if it doesn't exist.

**Comment by willingc** [comment]
Should we close @yuvipanda?

**Comment by consideRatio** [comment]
I think this is resolved by #49, let's close!
