### ISSUE TITLE
Can this be used with OAuth authenticator

### ISSUE THREAD

**Issue by ellisonbg** [jupyterhub/systemdspawner#14]
The README of this repo say that users have to already have local accounts on the system. However, when using the OAuth authenticator, local user accounts are created dynamically when the user first logs in. Will this approach with this authenticator?

**Comment by ixjlyons** [comment]
I'd like to know this definitively as well. From what I understand about the flow of jupyterhub, it seems with `c.LocalAuthenticator.create_system_users = True`, the user account should be created immediately after auth and before the spawner is involved, so it should work.

**Comment by minrk** [comment]
Yes, all the same Local*Authenticator should work with SystemdSpawner as LocalProcessSpawner.
