### ISSUE TITLE
404 : Not Found Error on Notebook start

### ISSUE THREAD

**Issue by astrodb** [jupyterhub/systemdspawner#22]
I'm trying to setup a basic Jupyterhub server that spawns notebooks locally using the systemdspawner.  I've gone through the installation of both according to the instructions, and my Jupyterhub server starts as expected.  But immediately after logging in I get an error:
404 : Not Found
You are requesting a page that does not exist!

I can't see anything relevant or problematic in the logs, but this is the first time I've played around with Jupyter so I'm probably missing something obvious...

I've attached a cleaned version of the jupyterhub_config.py file, the runtime log for the jupyterhub server (with debug options on), and the syslog from the time I tried to access the notebook through the server.

[404error-syslog.txt](https://github.com/jupyterhub/systemdspawner/files/1300020/404error-syslog.txt)
[hub-log-404error.txt](https://github.com/jupyterhub/systemdspawner/files/1300019/hub-log-404error.txt)

[jupyterhub_config-trimmed.txt](https://github.com/jupyterhub/systemdspawner/files/1299997/jupyterhub_config-trimmed.txt)

**Comment by willingc** [comment]
Hi @astrodb,

For a first time user of JupyterHub, I would recommend that you begin by deploying a basic JupyterHub following the instructions in the [Zero to JupyterHub guide](https://zero-to-jupyterhub.readthedocs.io/en/latest/index.html)

**Comment by astrodb** [comment]
Thanks, I've been through that document, and it was helpful in some areas, but I've no interest of getting this running on a cloud.  I have a single decently spec'd server I'd like to have a Jupyterhub service running on, that spawns notebooks on the bare metal.  We're looking at this as a possible data analysis solution for our research users, and putting the notebooks on a cloud isn't useful since they won't have access to our archives.  Setting up a cloud is in the cards, but not something we're doing right now.

Having walked through that document, and the official installation documentation, and extensive googling of possible problems, I'm stuck.  My hub server starts without listing any errors.  The notebook seems to start without any errors.  Yet the only thing I can see on a user page is the "404..." error.  I can go to the control panel and it lists all my users.  I can even access their servers, but this always results in the same "404" error.

**Comment by willingc** [comment]
Got it re: cloud. Let's see if we can isolate what is causing the 404. What version of jupyterhub and configurable_http_proxy are you using?

**Comment by astrodb** [comment]
Thanks.  The server is running Ubuntu 17.04. Here are the various Jupyter package versions installed through pip:

jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
jupyterhub (0.7.2)
jupyterhub-systemdspawner (0.9.10)

The proxy I'm using is the built in one that came with Jupyterhub.  I've installed nginx, and probably will use that if we take this into production, but figured I'd try to get things working with the default proxy as a start.

**Comment by astrodb** [comment]
Another user on my server doing the same thing is getting HTTP 500 errors, and this produces errors in the jupyterhub logs.  It might help debug it...  Log attached
[roy-error.txt](https://github.com/jupyterhub/systemdspawner/files/1302709/roy-error.txt)

**Comment by astrodb** [comment]
So it appears my problems were due to a combination of this: https://github.com/jupyter/notebook/issues/2056  and this: https://github.com/jupyterhub/jupyterhub/issues/1357  

The 404 and 500 erros are now resolved after reinstalling npm and adding "tree" to the base URL in the JupyterHub config file.

**Comment by willingc** [comment]
**Resolution** Resolve 404 and 500 errors by reinstalling npm and adding `tree` to the base URL.

Thanks @astrodb!
