### ISSUE TITLE
Blocking subprocess calls in coroutines

### ISSUE THREAD

**Issue by dbuse** [jupyterhub/systemdspawner#25]
Hi,

it looks like this spawner makes use of a lot of `subprocess.check_output` calls to start and stop singleuser instances within corountines. As long as everything works fine that seems to be okay. But if e.g. a shutdown takes longer, the whole hub seems to lag as the corountine blocks.
It looks as if there is an integrated subprocess module for tornado that might make these calls asynchronous, too, thus allowing to yield from the corountine. Might this be an improvent?

By the way, thanks for the great project!

**Comment by willingc** [comment]
Hi @dbuse, Thanks for the suggestion. Just curious, what configuration (system: os and cloud provider / bare metal) are you seeing the lags on?

**Comment by dbuse** [comment]
@willingc we are running Debian GNU/Linux 9.1 (stretch) on a VM inside our university's on-premise VMVare cluster. We are using the culling script from the jupyterhub docs to shutdown idle singleuser instances.

Maybe the actual problem lies with the singleuser instances that refuse to shutdown properly. Still, singleuser servers should not block the whole hub i guess.

**Comment by willingc** [comment]
Thanks @dbuse. What version of JupyterHub are you currently running?

cc/ @minrk have you seen the above behavior?

**Comment by dbuse** [comment]
@willingc: Thanks for your time. We're using:

- Jupyterhub 0.8.0
- notebook 5.2.0
- jupyterhub-systemdspawner rev 8d1b497 (current master at the time of writing)

all installed via pip

**Comment by yuvipanda** [comment]
I agree, subprocess.check_output is suboptimal and would cause the exact symptoms you are describing.

Switching to using tornado.subprocess is the right thing to do. I'm currently swamped with other work, unfortunately. Do you think you can take a shot at sending a PR? I promise to review that :)

Glad to hear systemdspawner is being useful!

**Comment by dbuse** [comment]
@yuvipanda: Yes, actually very useful. Thanks a lot for ths

I'll try to look into a PR utilizing tornado's subprocess handling on the weekend.
In the meantime a workaround was to add the '--no-block' flag to systemctl stop.

**Comment by minrk** [comment]
Yup, tornado subprocesses are exactly the thing for this.

**Comment by yuvipanda** [comment]
Fixed in #33, uses asyncio coroutines now.
