### ISSUE TITLE
Wrong version gets installed

### ISSUE THREAD

**Issue by lbiemans** [jupyterhub/systemdspawner#29]
If you run pip install jupyterhub-systemdspawner you get version 0.9.10 installed (see: https://pypi.python.org/pypi/jupyterhub-systemdspawner/0.9.10) which contains a bug with the conversion to the correct percentage e.g. 4.0 and 4 get converted to 400.0% and 0.12 gets converted to 12.0% (see: https://github.com/jupyterhub/systemdspawner/pull/24/commits/e127095988264caaf46c3f44b78203e04cf80576). The issue is easily solved by changing '--property=CPUQuota={quota}%'.format(quota=self.cpu_limit * 100) to '--property=CPUQuota={quota}%'.format(quota=int(self.cpu_limit * 100)) in systemdspawner.py

**Comment by yuvipanda** [comment]
Heya! I've made a few releases since, so this should be solved.

Thank you for opening the issue, and apologies for the long delay in resolving!
