### ISSUE TITLE
no way to define non-standard home directories

### ISSUE THREAD

**Issue by cpainterwakefield** [jupyterhub/systemdspawner#30]
Hi, I'm using jupyterhub with systemdspawner on a linux system where the home directories are mounted using some scheme that I have no control over and don't really understand (I have sudo privileges, but don't administer things like users).  The home directories for the users are *not* /home/{USERNAME}, and they are *not* all under the same parent directory.  E.g., my home directory is under /u/af/ci/{USERNAME}, but others are under /u/xx/yy/{USERNAME}, substitute whatever two letter string for xx and yy.

For now, I hacked the systemdspawner.py code to add an additional alias {USERHOME}, which is looked up via 
   os.path.expanduser('~' + self.user.name)

I know this is a horrible hack, but I don't know what else to do short term.  What is a better long term fix?  Can systemdspawner be modified to lookup user home directories as the default, instead of hardcoding as /home/{USERNAME}?

Thank you.

**Comment by dbuse** [comment]
Hi,
we had the same issue and worked around it by simply symlinking all homes to /home/{username}. Althogh a replacement makro for something resolving to $HOME or ~{username} would be both nice and possible.
Best.

**Comment by cpainterwakefield** [comment]
OK, when I have time I guess I'll put together a PR.  The symlink thing is impractical for me.

**Comment by yuvipanda** [comment]
Apologies for the delayed response! #34 makes homes default to whatever is in the password database, which should 'do the right thing'. I'll merge it shortly and make a new release!
