### ISSUE TITLE
PAM Authentication failed

### ISSUE THREAD

**Issue by mrmodolo** [jupyterhub/systemdspawner#35]
Hi!

I'm testing the 'systemd spawn' service but I always end up with an authentication error.
I check the following error logs:

Jul 15 21:05:40 jupyter jupyterhub: [W 2018-07-15 21:05:40.257 JupyterHub auth:618] PAM Authentication failed (modolo@192.168.122.1): [PAM Error 7] Authentication failure
Jul 15 21:05:40 jupyter jupyterhub: [W 2018-07-15 21:05:40.259 JupyterHub base:504] Failed login for modolo
Jul 15 21:05:40 jupyter jupyterhub: [I 2018-07-15 21:05:40.263 JupyterHub log:158] 200 POST /hub/login?next= (@192.168.122.1) 1808.99ms

The IP of the machine is '192.168.122.197/24' but by logging the authentication is done in modolo@192.168.122.1!

[modolo@jupyter ~]$ sudo cat /etc/systemd/system/jupyterhub.service 
[Service]
ExecStart=/opt/anaconda3/bin/jupyterhub --debug --ip 192.168.122.197 --no-ssl --config /etc/jupyterhub/jupyterhub_config.py
Environment=PATH=/opt/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
ReadOnlyDirectories=/
ReadWriteDirectories=/var/lib/jupyterhub /var/log/ /proc/self/ /var/local/lib/jupyterhub
WorkingDirectory=/var/local/lib/jupyterhub
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_AUDIT_WRITE CAP_SETGID CAP_SETUID
#PrivateDevices=yes
#PrivateTmp=yes

Thanks,
Marcelo Módolo

**Comment by consideRatio** [comment]
I'll go for a close on this as its a bit outdated to work now, but related to this is:

- #104 
- #81
