### ISSUE TITLE
Systemctl not found

### ISSUE THREAD

**Issue by dkipping** [jupyterhub/systemdspawner#42]
When trying to use the systemdspawner with the zero-to-jupyterhub helm chart, I provided my jupyterhub with an own hub image. The dockerfile of the custom hub-image looks like follows:
```
FROM jupyterhub/k8s-hub:0.7.0

RUN pip3 install wheel
RUN pip3 install jupyterhub-systemdspawner
```

So just installing the systemd spawner. Without installing wheel, the installation fails.

When trying to activate this in my `config.yaml` for _z2jh_ like this:
```
hub:
  # using customized hub image to integrate systemdspawner
  image:
    name: 'me/my-image'
    tag: 'my-tag'
  extraConfig: |
    # following lines for configuring the systemd spawner
    from systemdspawner import SystemdSpawner
    c.JupyterHub.spawner_class = SystemdSpawner
    c.SystemdSpawner.cpu_limit = 0.5
    c.SystemdSpawner.mem_limit = '20G'
    c.SystemdSpawner.isolate_tmp = True
    c.SystemdSpawner.isolate_devices = True
    c.SystemdSpawner.dynamic_users = True
```

And applying it via kubectl upgrade, the hub fails to spawn any single user servers with the following error message:
```
[I 2018-11-12 JupyterHub app:1673] Using Spawner: systemdspawner.systemdspawner.SystemdSpawner
...
[E 2018-11-12 JupyterHub app:1450] Failed to poll spawner for test, assuming the spawner is not running.
    Traceback (most recent call last):
      File "/home/jovyan/.local/lib/python3.6/site-packages/jupyterhub/app.py", line 1447, in check_spawner
        status = await spawner.poll()
      File "/home/jovyan/.local/lib/python3.6/site-packages/systemdspawner/systemdspawner.py", line 300, in poll
        if await systemd.service_running(self.unit_name):
      File "/home/jovyan/.local/lib/python3.6/site-packages/systemdspawner/systemd.py", line 79, in service_running
        stdout=asyncio.subprocess.DEVNULL
      File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
        stderr=stderr, **kwds)
      File "/usr/lib/python3.6/asyncio/base_events.py", line 1192, in subprocess_exec
        bufsize, **kwargs)
      File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
        **kwargs)
      File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
        stderr=stderr, bufsize=bufsize, **kwargs)
      File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
        universal_newlines=False, bufsize=bufsize, **kwargs)
      File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'systemctl': 'systemctl'
```

Seems that systemctl and therefore systemd is not available / running.
Do I have to install it to the hub or is there some trick to activate it?

Either way this should maybe be added to the documentation / the README installation guide here, so these dependencies are clear for the user and he/she does not spend too much time on searching to resolve the setup.

**Comment by ixjlyons** [comment]
Sorry to answer your questions with another question, but why do you need to use systemdspawner when you're running a Docker-based setup? You should be able to set resource limits and such directly in your `config.yaml`: https://zero-to-jupyterhub.readthedocs.io/en/stable/user-resources.html

As far as I know, using systemd inside Docker containers isn't usually necessary/useful, and systemdspawner in particular is provided for cases where you don't want a containerized setup. From the README (emphasis mine):

> If you want to use Linux Containers (Docker, rkt, etc) for isolation and security benefits, but **don't want the headache and complexity of container image management**, then you should use the SystemdSpawner

**Comment by ixjlyons** [comment]
Ah, I'm pretty sure z2jh uses [kubespawner](https://github.com/jupyterhub/kubespawner), which supports resource allocation through kubernetes. I'm a little out of my element here (only deployed JupyterHub in small-scale single-server environments), so you might want to wait around for a more involved JupyterHub person to help out.
