### ISSUE TITLE
Check systemd-run version to make sure it is new enough

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/systemdspawner#6]
According to https://github.com/systemd/systemd/blob/master/NEWS,
1. We need at least systemd 211 to use systemd-run
2. We need at least systemd 217 to isolate /tmp for all the notebook services

**Comment by fchiriac** [comment]
Hello guys, i am also facing the same issue with systemdspawner on a Ubuntu 18.04 LTS VM ( Not docker ) with systemd 237 and can successfully spawn notebooks using the default local process spawner but once i try to enable the newly installed jupyterhub-systemdspawner i get an error and the hub won`t start anymore stating the follwing : 

 The 'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7f1fe4ae7b38> instance must be a type, but 'systemdspawner.SystemdSpawner' could not be imported

Any insights over this matter will be highly appreciated. 

Thanks
