### ISSUE TITLE
Figure out what to do if we try to start a service that already exists

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/systemdspawner#7]
Right now it fails as a 503. Ideally this should not happen, but it does - for example when the hub dies and doesn't clean up. Perhaps it should pick them up when it reboots.

**Comment by yuvipanda** [comment]
Currently fails with: 

```
Failed to start transient service unit: Unit jupyter-test-singleuser.service already exists.
```

Should instead stop the old service & start a new one.

**Comment by hansen-m** [comment]
I'm currently seeing this issue with one user. As an admin, is there a way to check if the service already exists and force a stop?
