### ISSUE TITLE
Git tag vor version 0.15.0

### ISSUE THREAD

**Issue by erictapen** [jupyterhub/systemdspawner#89]
### Bug description

It looks like there wasn't a corresponding git tag released for the [newest version 0.15.0 at Pypi](https://pypi.org/project/jupyterhub-systemdspawner/#history). Could you add that? It makes maintaining the systemdspawner package at Nixpkgs much easier.

**Comment by yuvipanda** [comment]
I just tagged v0.15 at 7d7cf42db76d9cfa5a4bc42fff14943877ac570b. Thanks for pointing this out, @erictapen!
